#!/bin/bash

for TRAY_PATH in /usr/lib/python*/site-packages/proton/vpn/app/gtk/assets/icons; do
    [[ -d "$TRAY_PATH" ]] && break
done

[[ -d "$TRAY_PATH" ]] || { echo "ProtonVPN not installed"; exit 0; }
echo "Running proton-vpn tray-icon theme fix..."

echo "Removing ProtonVPN's tray icons. Sudo is needed..."
sudo rm -rf "$TRAY_PATH/state-connected.svg" "$TRAY_PATH/state-disconnected.svg" "$TRAY_PATH/state-error.svg"

echo 'Copying new icons...'
sudo cp state-connected.svg $TRAY_PATH
sudo cp state-disconnected.svg $TRAY_PATH
sudo cp state-error.svg $TRAY_PATH

echo 'Done.'
