#size	xhot	yhot	Path to PNG image	delay
24	26	26	/tmp/tmp.crSGhHkqal/bottom_right_corner_000.png	50
36	35	35	/tmp/tmp.crSGhHkqal/bottom_right_corner_001.png	50
48	52	52	/tmp/tmp.crSGhHkqal/bottom_right_corner_002.png	50
