#size	xhot	yhot	Path to PNG image	delay
24	4	26	/tmp/tmp.wwDZqlzIY8/bottom_left_corner_000.png	50
36	6	35	/tmp/tmp.wwDZqlzIY8/bottom_left_corner_001.png	50
48	8	52	/tmp/tmp.wwDZqlzIY8/bottom_left_corner_002.png	50
