#size	xhot	yhot	Path to PNG image	delay
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_000.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_001.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_002.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_003.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_004.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_005.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_006.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_007.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_008.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_009.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_010.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_011.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_012.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_013.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_014.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_015.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_016.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_017.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_018.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_019.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_020.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_021.png	30
24	4	4	/tmp/tmp.NjKoHw3gTN/progress_022.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_023.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_024.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_025.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_026.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_027.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_028.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_029.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_030.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_031.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_032.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_033.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_034.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_035.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_036.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_037.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_038.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_039.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_040.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_041.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_042.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_043.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_044.png	30
36	6	6	/tmp/tmp.NjKoHw3gTN/progress_045.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_046.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_047.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_048.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_049.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_050.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_051.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_052.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_053.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_054.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_055.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_056.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_057.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_058.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_059.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_060.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_061.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_062.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_063.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_064.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_065.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_066.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_067.png	30
48	8	8	/tmp/tmp.NjKoHw3gTN/progress_068.png	30
