#size	xhot	yhot	Path to PNG image	delay
24	5	4	/tmp/tmp.z50xr0fuUC/top_left_corner_000.png	50
36	8	6	/tmp/tmp.z50xr0fuUC/top_left_corner_001.png	50
48	10	8	/tmp/tmp.z50xr0fuUC/top_left_corner_002.png	50
