#size	xhot	yhot	Path to PNG image	delay
24	16	16	/tmp/tmp.ASU3kDKF5I/vertical-text_000.png	50
36	24	24	/tmp/tmp.ASU3kDKF5I/vertical-text_001.png	50
48	32	32	/tmp/tmp.ASU3kDKF5I/vertical-text_002.png	50
