#!/bin/bash

## Obsidian
sudo sed -i "s/Exec=\/usr\/bin\/obsidian %U/Exec=\/usr\/bin\/obsidian OBSIDIAN_USE_WAYLAND=1 -enable-features=UseOzonePlatform -ozone-platform=wayland %U/" /usr/share/applications/obsidian.desktop
