#!/bin/bash

# Normally when trying to cycle window focus and change from floating to tiled
# or vice versa, you end up having to cycle between multiple windows until
# you finally change the focus to tiled or float.
# With this, it should change to tiled if you're in floating, and floating if you're int tiled

TEMP="/tmp/cycle-float-tile"

# Create temporary file if it doesn't exist
if [[ ! -e $TEMP ]]; then 
  touch $TEMP
fi

# make sure it has 2 empty lines first
while [[ $(wc -l < "$TEMP") -lt 2 ]]; do
    echo "" >> "$TEMP"
done

# check if floating or tiled
floating=$(hyprctl -j activewindow | jq -r '.floating')

# if its tiled:
if [[ "$floating" == "false" ]]; then
  echo 'Saving active window address'
  activeaddress=$(hyprctl -j activewindow | jq -r '.address')

  # write tiled address to first line
  sed -i "1s/.*/$activeaddress/" "$TEMP"

  # read float address from second line
  prevaddress=$(sed -n '2p' "$TEMP")
  # if window address exists
  if [[ -n "$prevaddress" ]]; then # trim whitespace
    # only change to window address if on the same workspace
    activeworkspace=$(hyprctl -j activeworkspace | jq -r '.id')
    addressworkspace=$(hyprctl -j clients | jq -r ".[] | select(.address == \"$prevaddress\") | .workspace.id")
    if [[ "$activeworkspace" == "$addressworkspace" ]]; then
      # if window is not found exit code is still 0 for some reason, so we have to read output manually
      output=$(hyprctl dispatch focuswindow address:"$prevaddress" 2>&1)
    else
      hyprctl dispatch cyclenext floating
    fi
    if [[ "$output" == *"No such window found"* ]]; then
      hyprctl dispatch cyclenext floating
    fi
  else
    hyprctl dispatch cyclenext floating
  fi

# if its floating:
elif [[ "$floating" == "true" ]]; then
  echo 'Saving active window address'
  activeaddress=$(hyprctl -j activewindow | jq -r '.address')

  # write float address to second line
  sed -i "2s/.*/$activeaddress/" "$TEMP"

  # read tiled address from first line
  prevaddress=$(sed -n '1p' "$TEMP")
  # if window address exists
  if [[ -n "$prevaddress" ]]; then # trim whitespace
    # only change to window address if on the same workspace
    activeworkspace=$(hyprctl -j activeworkspace | jq -r '.id')
    addressworkspace=$(hyprctl -j clients | jq -r ".[] | select(.address == \"$prevaddress\") | .workspace.id")
    if [[ "$activeworkspace" == "$addressworkspace" ]]; then
      # if window is not found exit code is still 0 for some reason, so we have to read output manually
      output=$(hyprctl dispatch focuswindow address:"$prevaddress" 2>&1)
    else
      hyprctl dispatch cyclenext tiled
    fi
    if [[ "$output" == *"No such window found"* ]]; then
      hyprctl dispatch cyclenext tiled
    fi
  else
    hyprctl dispatch cyclenext tiled
  fi
fi
