#!/bin/bash

if [[ "$1" == opacityp ]]; then
  opacity=$(hyprctl getprop active opacity)
  if [[ "$opacity" < 1 ]]; then
    hyprctl dispatch setprop active opacity $(echo "$opacity" + 0.1 | bc) $(echo "$opacity" + 0.1 | bc)
    exit 0
  fi
fi

if [[ "$1" == opacitym ]]; then
  opacity=$(hyprctl getprop active opacity)
  if [[ "$opacity" > 0 ]]; then
    hyprctl dispatch setprop active opacity $(echo "$opacity" - 0.1 | bc) $(echo "$opacity" - 0.1 | bc)
    exit 0
  fi
fi

if [[ "$1" == blur ]]; then
  if $(hyprctl getprop active no_blur); then
    hyprctl dispatch setprop active no_blur 0
  else
    hyprctl dispatch setprop active no_blur 1
  fi
  exit 0
fi

if [[ "$1" == blur-all ]]; then
  # Get the specific line containing 'int:' and extract the number
  blur_status=$(hyprctl getoption decoration:blur:enabled | awk '/int:/ {print $2}')

  # Check the value and run the commands
  if [ "$blur_status" -eq 1 ]; then
    # Blur for all windows is currently ENABLED. Disabling...
    hyprctl keyword decoration:blur:enabled false
  elif [ "$blur_status" -eq 0 ]; then
    # Blur for all windows is currently DISABLED. Enabling...
    hyprctl keyword decoration:blur:enabled true
  else
    echo "Something went wrong! Unexpected output: $blur_status"
  fi
  exit 0
fi
