#!/bin/bash

TRAY_PATH="/opt/YouTube Music/resources/app.asar.unpacked/assets"

[[ -d "$TRAY_PATH" ]] || ( echo "Tray path doesn't exist. Pear desktop prob not installed" && exit 0 )

echo 'Removing default tray icon, sudo is needed...'
sudo rm -rf "$TRAY_PATH/youtube-music-tray.png" "$TRAY_PATH/youtube-music-tray-paused.png"

echo 'Replacing with custom icon...'
sudo cp youtube-music-tray.png "$TRAY_PATH/youtube-music-tray.png"
sudo cp youtube-music-tray.png "$TRAY_PATH/youtube-music-tray-paused.png"

echo 'Done.'
