max-gamma = 150

profile {
    time = 6:30
    identity = true
}

profile {
    time = 18:00
    temperature = 5900
}

profile {
    time = 18:10
    temperature = 5800
    gamma = 0.99
}

profile {
    time = 18:20
    temperature = 5700
    gamma = 0.98
}

profile {
    time = 18:35
    temperature = 5600
    gamma = 0.97
}

profile {
    time = 18:50
    temperature = 5500
    gamma = 0.96
}

profile {
    time = 19:00
    temperature = 5400
    gamma = 0.95
}

profile {
    time = 19:30
    temperature = 5300
    gamma = 0.94
}

profile {
    time = 20:00
    temperature = 5200
    gamma = 0.92
}

profile {
    time = 20:30
    temperature = 5100
    gamma = 0.91
}

profile {
    time = 21:00
    temperature = 5000
    gamma = 0.90
}
