# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#bfc8cc"

# Title color for boxes
theme[title]="#cfd8dc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#00ffff"

# Background color of selected item in processes box
theme[selected_bg]="#690085"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#40"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ff0000"
# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#cfd8dc"

## Outlines
# Cpu box outline color
theme[cpu_box]="#490085"

# Gpu color doesn't seem to exist?
theme[gpu_box]="#ff0000"

# Memory/disks box outline color
theme[mem_box]="#005090"

# Net up/down box outline color
theme[net_box]="#005090"

# Processes box outline color
theme[proc_box]="#005090"

# Box divider line and small boxes line color
theme[div_line]="#516176"

# Temperature graph colors
# theme[temp_start]="#00bcd4"
# theme[temp_mid]="#d4d400"
# theme[temp_end]="#ff0040"

# CPU graph colors
theme[cpu_start]="#b911b9"
theme[cpu_mid]="#00bcd4"
theme[cpu_end]="#ff0040"

# Mem/Disk free meter
theme[free_start]="#00cfb7"
theme[free_mid]="#00bfc0"
theme[free_end]="#00adc2"

# Mem/Disk cached meter
theme[cached_start]="#009cc1"
theme[cached_mid]="#008bbe"
theme[cached_end]="#007bbc"

# Mem/Disk available meter
theme[available_start]="#0066c7"
theme[available_mid]="#314ebc"
theme[available_end]="#5632a4"

# Mem/Disk used meter
theme[used_start]="#690085"
theme[used_mid]="#bc0288"
theme[used_end]="#ff4080"

# Download graph colors
theme[download_start]="#00bcd4"
theme[download_mid]="#991199"
theme[download_end]="#ff4080"

# Upload graph colors
theme[upload_start]="#00bcd4"
theme[upload_mid]="#991199"
theme[upload_end]="#ff4080"

# Process box color gradients for threads, men, and cpu usage
theme[process_start]="#00cfb7"
